<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>558beb9a-4c2c-4058-8b8a-ffe70c7103e6</testSuiteGuid>
   <testCaseLink>
      <guid>40b4c22e-115b-4a4d-920d-cd56715f0f03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Verify that users can successfully log in with valid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93dd36b1-f5d5-4d0f-9ffd-2ccbf3174c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb54e30e-9e31-477c-93f3-211f09afa389</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b00c600c-5ef8-420c-ac05-2454efa1401e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Verify that users can not successfully log in with invalid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6a03876-57ef-4a79-8899-0897bf57ec03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80b0e564-ca11-4a4f-9ec6-e89e719ade96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a601abb1-e3be-4518-9769-494fecbd30e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48126ea1-1dea-4782-9229-e7ec5b38e948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a6cb681-11e5-43c4-8634-cadd8ecdfaf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bce3fa6e-5042-4c1c-99c5-1af4d2eca978</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Product detail should be shown when click product image</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44835227-0ad1-4b1d-859f-b857f353e6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87c9556-89e4-4b13-9d36-e9cf086ae5fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e2a572-7278-4923-9ec2-ff46a525dbc1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a724e9-b239-4c62-a608-d03cb05955dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Product detail should be shown when click product name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>739a5222-9c26-4241-85c4-d5b0b04bc16c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a005d7ae-00e6-4173-abc7-3fff9346061d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d3f4bad-26df-43bd-a45e-6a94f985020d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0794a6aa-3271-4b50-b36f-77a070962f8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Product will move to shopping cart after clicking add-to-cart button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ae4c77-8ee7-46c5-a1d5-1bd01a3d0524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9d08c75-b774-4590-9f7b-8d85f78dee62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8290cdfc-62fa-4ab6-b397-05b43e5e306a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cd56c52-fe08-4ba0-bb10-9e1685407076</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Verify that product is removed when delete from shopping cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee5f48e-55ce-4519-9c6f-edcac87c513c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95927a1e-e958-4843-9ce0-467181f48df7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d571ebc0-f45e-4bd0-87b6-d9cf93a5318b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a6b5c3e-b2f6-4ac8-8785-1722c02c719f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Verify that user can add and order successfully</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af92b605-2c1d-4dce-8126-b003aedfaac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51098c8a-a440-43b1-84c4-e313f8583ad5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443a8b2c-5eb3-4a47-81bd-983b0d8c2e63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2750fbf8-f2ca-491d-92fb-b5bf4b649818</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Verify that user can sort product by dropdown</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>286821c4-3b99-4936-8e92-52b08317ffc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571d31c3-b677-4f6f-8802-294664936fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>532d5920-3f05-4165-8ed9-86735eb49a5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66fa21b0-540a-4082-b4fc-2f4ef156d74a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
